# =============================================================================
# Tests
# =============================================================================

add_library(imcsim-tests
        STATIC
            #
)

target_include_directories(imcsim-tests
        PUBLIC
            ${CMAKE_CURRENT_SOURCE_DIR}
)

target_link_libraries(imcsim-tests
        PUBLIC
            #
)

# =============================================================================
# End of file
# =============================================================================
